USE is31r;
-- Таблица REGIUNI
CREATE TABLE REGIUNI (
    ID_REGIUNE INT PRIMARY KEY,
    DENUMIRE_REGIUNE VARCHAR(25) NOT NULL
);

-- Таблица TARI
CREATE TABLE TARI (
    ID_TARA CHAR(2) PRIMARY KEY,
    DENUMIRE_TARA VARCHAR(40) NOT NULL,
    ID_REGIUNE INT NOT NULL,
    FOREIGN KEY (ID_REGIUNE) REFERENCES REGIUNI(ID_REGIUNE)
);

-- Таблица LOCATII
CREATE TABLE LOCATII (
    ID_LOCATIE INT PRIMARY KEY,
    ADRESA VARCHAR(40) NOT NULL,
    COD_POSTAL VARCHAR(10) NOT NULL,
    ORAS VARCHAR(25) NOT NULL,
    ZONA VARCHAR(25) NOT NULL,
    ID_TARA CHAR(2) NOT NULL,
    FOREIGN KEY (ID_TARA) REFERENCES TARI(ID_TARA)
);

-- Таблица FUNCTИИ
CREATE TABLE FUNCTII (
    ID_FUNCTIE VARCHAR(10) PRIMARY KEY,
    DENUMIRE_FUNCT VARCHAR(35) NOT NULL,
    SALARIU_MIN INT NOT NULL,
    SALARIU_MAX INT NOT NULL
);

-- Таблица ANGAJATI
CREATE TABLE ANGAJATI (
    ID_ANGAJAT INT PRIMARY KEY,
    PRENUME VARCHAR(20) NOT NULL,
    NUMЕ VARCHAR(25) NOT NULL,
    TELEФОН VARCHAR(20),
    EMAIL VARCHAR(50),
    DATA_ANGAJARE DATE NOT NULL,
    ID_FUNCTIE VARCHAR(10) NOT NULL,
    SALARIU DECIMAL(8,2) NOT NULL,
    COMISION DECIMAL(5,2),
    ID_MANAGER INT,
    ID_DEPARTAMENT INT,
    FOREIGN KEY (ID_FUNCTIE) REFERENCES FUNCTII(ID_FUNCTIE),
    FOREIGN KEY (ID_MANAGER) REFERENCES ANGAJATI(ID_ANGAJAT)
);

-- Таблица DEPARTAMENTE
CREATE TABLE DEPARTAMENTE (
    ID_DEPARTAMENT INT PRIMARY KEY,
    DENUMIRE_DEPARTAMENT VARCHAR(30) NOT NULL,
    ID_MANAGER INT,
    ID_LOCATIE INT NOT NULL,
    FOREIGN KEY (ID_MANAGER) REFERENCES ANGAJATI(ID_ANGAJAT),
    FOREIGN KEY (ID_LOCATIE) REFERENCES LOCATII(ID_LOCATIE)
);

-- Таблица ISTORIC_FUNCTII
CREATE TABLE ISTORIC_FUNCTII (
    ID_ANGAJAT INT NOT NULL,
    DATA_INCEPUT DATE NOT NULL,
    DATA_SFARSIT DATE,
    ID_FUNCTIE VARCHAR(10) NOT NULL,
    ID_DEPARTAMENT INT NOT NULL,
    FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJATI(ID_ANGAJAT),
    FOREIGN KEY (ID_FUNCTIE) REFERENCES FUNCTII(ID_FUNCTIE),
    FOREIGN KEY (ID_DEPARTAMENT) REFERENCES DEPARTAMENTE(ID_DEPARTAMENT),
    PRIMARY KEY (ID_ANGAJAT, DATA_INCEPUT)
);

-- Таблица CLIENTI
CREATE TABLE CLIENTI (
    ID_CLIENT INT PRIMARY KEY,
    PRENUME_CLIENT VARCHAR(20) NOT NULL,
    NUME_CLIENT VARCHAR(20) NOT NULL,
    TELEФОН VARCHAR(20),
    LIMITA_CREDIT DECIMAL(8,2),
    EMAIL_CLIENT VARCHAR(30),
    DATA_NASTERE DATE,
    STAREA_CIVILA VARCHAR(10),
    SEX CHAR(1),
    NIVEL_VENITURI VARCHAR(20)
);

-- Таблица PRODUSE
CREATE TABLE PRODUSE (
    ID_PRODUS INT PRIMARY KEY,
    DENUMIRE_PRODUS VARCHAR(50) NOT NULL,
    DESCRIERE VARCHAR(200),
    CATEGORIE VARCHAR(40),
    PRET_LISTA DECIMAL(8,2) NOT NULL,
    PRET_MIN DECIMAL(8,2) NOT NULL
);

-- Таблица COMENZI
CREATE TABLE COMENZI (
    NR_COMANDA INT PRIMARY KEY,
    DATA TIMESTAMP NOT NULL,
    MODALITATE VARCHAR(20),
    ID_CLIENT INT NOT NULL,
    STARE_COMANDA TINYINT,
    ID_ANGAJAT INT NOT NULL,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTI(ID_CLIENT),
    FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJATI(ID_ANGAJAT)
);

-- Таблица RAND_COMENZI
CREATE TABLE RAND_COMENZI (
    NR_COMANDA INT NOT NULL,
    ID_PRODUS INT NOT NULL,
    PRET DECIMAL(8,2) NOT NULL,
    CANTITATE INT NOT NULL,
    FOREIGN KEY (NR_COMANDA) REFERENCES COMENZI(NR_COMANDA),
    FOREIGN KEY (ID_PRODUS) REFERENCES PRODUSE(ID_PRODUS),
    PRIMARY KEY (NR_COMANDA, ID_PRODUS)
);
